INSERT INTO artist(name) VALUES('Meshuggah');
INSERT INTO artist(name) VALUES('TesseracT');
INSERT INTO artist(name) VALUES('Scar Symmetry');
INSERT INTO artist(name) VALUES('Arch Enemy');
INSERT INTO artist(name) VALUES('Fear Factory');
INSERT INTO artist(name) VALUES('Disturbed');
INSERT INTO artist(name) VALUES('Slipknot');
INSERT INTO artist(name) VALUES('Children of Bodom');
INSERT INTO artist(name) VALUES('Testament');

INSERT INTO genre(name) VALUES('Math metal');
INSERT INTO genre(name) VALUES('Melodic death');
INSERT INTO genre(name) VALUES('Industrial metal');
INSERT INTO genre(name) VALUES('Metalcore');
INSERT INTO genre(name) VALUES('Nu metal');
INSERT INTO genre(name) VALUES('Thrash metal');

INSERT INTO album(name, year) VALUES('Obzen', 2008);
INSERT INTO album(name, year) VALUES('One', 2011);
INSERT INTO album(name, year) VALUES('Pitch Black Progress', 2006);
INSERT INTO album(name, year) VALUES('Anthems of Rebellion', 2003);
INSERT INTO album(name, year) VALUES('Genexus', 2015);
INSERT INTO album(name, year) VALUES('Immortalized', 2015);
INSERT INTO album(name, year) VALUES('Slipknot', 1999);
INSERT INTO album(name, year) VALUES('Follow The Reaper', 2000);
INSERT INTO album(name, year) VALUES('The Gathering', 2018);

INSERT INTO genreartists(genre_id, artist_id) VALUES(1, 1);
INSERT INTO genreartists(genre_id, artist_id) VALUES(1, 2);
INSERT INTO genreartists(genre_id, artist_id) VALUES(2, 3);
INSERT INTO genreartists(genre_id, artist_id) VALUES(2, 4);
INSERT INTO genreartists(genre_id, artist_id) VALUES(3, 5);
INSERT INTO genreartists(genre_id, artist_id) VALUES(5, 6);
INSERT INTO genreartists(genre_id, artist_id) VALUES(4, 7);
INSERT INTO genreartists(genre_id, artist_id) VALUES(2, 8);
INSERT INTO genreartists(genre_id, artist_id) VALUES(6, 9);

INSERT INTO albumartists(artist_id, album_id) VALUES(1, 1);
INSERT INTO albumartists(artist_id, album_id) VALUES(2, 2);
INSERT INTO albumartists(artist_id, album_id) VALUES(3, 3);
INSERT INTO albumartists(artist_id, album_id) VALUES(4, 4);
INSERT INTO albumartists(artist_id, album_id) VALUES(5, 5);
INSERT INTO albumartists(artist_id, album_id) VALUES(6, 6);
INSERT INTO albumartists(artist_id, album_id) VALUES(7, 7);
INSERT INTO albumartists(artist_id, album_id) VALUES(8, 8);
INSERT INTO albumartists(artist_id, album_id) VALUES(9, 9);


INSERT INTO track(name, duration, album_id) VALUES('Combustion', 248, 1);
INSERT INTO track(name, duration, album_id) VALUES('Electric Red', 351, 1);
INSERT INTO track(name, duration, album_id) VALUES('Bleed', 444, 1);
INSERT INTO track(name, duration, album_id) VALUES('Lethargica', 347, 1);
INSERT INTO track(name, duration, album_id) VALUES('Obzen', 264, 1);
INSERT INTO track(name, duration, album_id) VALUES('This Spiteful Snake', 292, 1);
INSERT INTO track(name, duration, album_id) VALUES('Pineal Gland Optics', 312, 1);
INSERT INTO track(name, duration, album_id) VALUES('Pravus', 310, 1);
INSERT INTO track(name, duration, album_id) VALUES('Dancers to a Discordant System', 576, 1);
INSERT INTO track(name, duration, album_id) VALUES('Lament', 293, 2);
INSERT INTO track(name, duration, album_id) VALUES('Nascent', 249, 2);
INSERT INTO track(name, duration, album_id) VALUES('Acceptance - Concealing Fate, Pt.1', 513, 2);
INSERT INTO track(name, duration, album_id) VALUES('Deception - Concealing Fate, Pt.2', 322, 2);
INSERT INTO track(name, duration, album_id) VALUES('The Impossible - Concealing Fate, Pt.3', 290, 2);
INSERT INTO track(name, duration, album_id) VALUES('Perfection - Concealing Fate, Pt.4', 158, 2);
INSERT INTO track(name, duration, album_id) VALUES('Epiphany - Concealing Fate, Pt.5', 89, 2);
INSERT INTO track(name, duration, album_id) VALUES('Origin - Concealing Fate, Pt.6', 284, 2);
INSERT INTO track(name, duration, album_id) VALUES('Sunrise', 237, 2);
INSERT INTO track(name, duration, album_id) VALUES('April', 289, 2);
INSERT INTO track(name, duration, album_id) VALUES('Eden', 548, 2);
INSERT INTO track(name, duration, album_id) VALUES('The Illusionist', 271, 3);
INSERT INTO track(name, duration, album_id) VALUES('Slaves to the Sublimal', 301, 3);
INSERT INTO track(name, duration, album_id) VALUES('Mind Machine', 234, 3);
INSERT INTO track(name, duration, album_id) VALUES('Pitch Black Progress',206, 3);
INSERT INTO track(name, duration, album_id) VALUES('Calculate the Apocalypse', 241, 3);
INSERT INTO track(name, duration, album_id) VALUES('Dreaming 24/7', 251, 3);
INSERT INTO track(name, duration, album_id) VALUES('Abstracted', 205, 3);
INSERT INTO track(name, duration, album_id) VALUES('The Kaleidoscopic God', 429, 3);
INSERT INTO track(name, duration, album_id) VALUES('Retaliator', 253, 3);
INSERT INTO track(name, duration, album_id) VALUES('Oscillation Point', 244, 3);
INSERT INTO track(name, duration, album_id) VALUES('The Path of Least Resistance', 269, 3);
INSERT INTO track(name, duration, album_id) VALUES('Carved in Stone (bonus track)', 328, 3);
INSERT INTO track(name, duration, album_id) VALUES('Deviate from the Form (bonus track)', 326, 3);
INSERT INTO track(name, duration, album_id) VALUES('Tear Down the Walls', 32, 4);
INSERT INTO track(name, duration, album_id) VALUES('Silent Wars', 255, 4);
INSERT INTO track(name, duration, album_id) VALUES('We Will Rise', 247, 4);
INSERT INTO track(name, duration, album_id) VALUES('Dead Eyes See No Future', 254, 4);
INSERT INTO track(name, duration, album_id) VALUES('Instinct', 218, 4);
INSERT INTO track(name, duration, album_id) VALUES('Leader of the Rats', 261, 4);
INSERT INTO track(name, duration, album_id) VALUES('Exist to Exit', 322, 4);
INSERT INTO track(name, duration, album_id) VALUES('Marching on a Dead End Road', 77, 4);
INSERT INTO track(name, duration, album_id) VALUES('Despicable Heroes', 132, 4);
INSERT INTO track(name, duration, album_id) VALUES('End of the Line', 216, 4);
INSERT INTO track(name, duration, album_id) VALUES('Dehumanization', 255, 4);
INSERT INTO track(name, duration, album_id) VALUES('Anthem', 57, 4);
INSERT INTO track(name, duration, album_id) VALUES('Saints and Sinners', 281, 4);
INSERT INTO track(name, duration, album_id) VALUES('Autonomous Combat System', 328, 5);
INSERT INTO track(name, duration, album_id) VALUES('Anodized', 287, 5);
INSERT INTO track(name, duration, album_id) VALUES('Dielectric', 259, 5);
INSERT INTO track(name, duration, album_id) VALUES('Soul Hacker', 192, 5);
INSERT INTO track(name, duration, album_id) VALUES('Protomech', 296, 5);
INSERT INTO track(name, duration, album_id) VALUES('Genexus', 288, 5);
INSERT INTO track(name, duration, album_id) VALUES('Church of Execution', 201, 5);
INSERT INTO track(name, duration, album_id) VALUES('Regenerate', 242, 5);
INSERT INTO track(name, duration, album_id) VALUES('Battle for Utopia', 254, 5);
INSERT INTO track(name, duration, album_id) VALUES('Expiration Date', 528, 5);
INSERT INTO track(name, duration, album_id) VALUES('The Eye of the Storm', 80, 6);
INSERT INTO track(name, duration, album_id) VALUES('Immortalized', 257, 6);
INSERT INTO track(name, duration, album_id) VALUES('The Vengeful One', 252, 6);
INSERT INTO track(name, duration, album_id) VALUES('Open Your Eyes', 237, 6);
INSERT INTO track(name, duration, album_id) VALUES('The Light', 256, 6);
INSERT INTO track(name, duration, album_id) VALUES('What Are You Waiting For', 243, 6);
INSERT INTO track(name, duration, album_id) VALUES('You''re Mine', 295, 6);
INSERT INTO track(name, duration, album_id) VALUES('Who', 286, 6);
INSERT INTO track(name, duration, album_id) VALUES('Save Our Last Goodbye', 299, 6);
INSERT INTO track(name, duration, album_id) VALUES('Fire It Up', 245, 6);
INSERT INTO track(name, duration, album_id) VALUES('The Sound of Silence', 248, 6);
INSERT INTO track(name, duration, album_id) VALUES('Never Wrong', 213, 6);
INSERT INTO track(name, duration, album_id) VALUES('Who Taught You How to Hate', 297, 6);
INSERT INTO track(name, duration, album_id) VALUES('742617000027', 36, 7);
INSERT INTO track(name, duration, album_id) VALUES('(sic)', 199, 7);
INSERT INTO track(name, duration, album_id) VALUES('Eyeless', 236, 7);
INSERT INTO track(name, duration, album_id) VALUES('Wait and Bleed', 147, 7);
INSERT INTO track(name, duration, album_id) VALUES('Surfacing', 218, 7);
INSERT INTO track(name, duration, album_id) VALUES('Spit It Out', 159, 7);
INSERT INTO track(name, duration, album_id) VALUES('Tattered & Torn', 174, 7);
INSERT INTO track(name, duration, album_id) VALUES('Frail Limb Nursery', 45, 7);
INSERT INTO track(name, duration, album_id) VALUES('Purity', 254, 7);
INSERT INTO track(name, duration, album_id) VALUES('Liberate', 186, 7);
INSERT INTO track(name, duration, album_id) VALUES('Prosthetics', 298, 7);
INSERT INTO track(name, duration, album_id) VALUES('No Life', 167, 7);
INSERT INTO track(name, duration, album_id) VALUES('Diluted', 203, 7);
INSERT INTO track(name, duration, album_id) VALUES('Only One', 146, 7);
INSERT INTO track(name, duration, album_id) VALUES('Scissors', 1155, 7);
INSERT INTO track(name, duration, album_id) VALUES('Follow the Reaper', 227, 8);
INSERT INTO track(name, duration, album_id) VALUES('Bodom After Midnight', 223, 8);
INSERT INTO track(name, duration, album_id) VALUES('Children of Decadence', 334, 8);
INSERT INTO track(name, duration, album_id) VALUES('Everytime I Die', 242, 8);
INSERT INTO track(name, duration, album_id) VALUES('Mask of Sanity', 238, 8);
INSERT INTO track(name, duration, album_id) VALUES('Taste of My Scythe', 237, 8);
INSERT INTO track(name, duration, album_id) VALUES('Hate Me!', 284, 8);
INSERT INTO track(name, duration, album_id) VALUES('Northern Comfort', 227, 8);
INSERT INTO track(name, duration, album_id) VALUES('Kissing the Shadows', 272, 8);
INSERT INTO track(name, duration, album_id) VALUES('D.N.R. (Do Not Resuscitate)', 214, 9);
INSERT INTO track(name, duration, album_id) VALUES('Down for Life', 203, 9);
INSERT INTO track(name, duration, album_id) VALUES('Eyes of Wrath', 326, 9);
INSERT INTO track(name, duration, album_id) VALUES('True Believer', 216, 9);
INSERT INTO track(name, duration, album_id) VALUES('3 Days in Darkness', 281, 9);
INSERT INTO track(name, duration, album_id) VALUES('Legions of the Dead', 157, 9);
INSERT INTO track(name, duration, album_id) VALUES('Careful What You Wish For', 210, 9);
INSERT INTO track(name, duration, album_id) VALUES('Riding the Snake', 253, 9);
INSERT INTO track(name, duration, album_id) VALUES('Allegiance', 157, 9);
INSERT INTO track(name, duration, album_id) VALUES('Sewn Shut Eyes', 255, 9);
INSERT INTO track(name, duration, album_id) VALUES('Fall of Sipledome', 288, 9);

INSERT INTO collection(name, year) VALUES('Math metal best', 2018);
INSERT INTO collection(name, year) VALUES('Industrial metal best', 2019);
INSERT INTO collection(name, year) VALUES('Melodic death best', 2020);
INSERT INTO collection(name, year) VALUES('Metalcore best', 2021);
INSERT INTO collection(name, year) VALUES('Nu metal', 2017);
INSERT INTO collection(name, year) VALUES('Ballades from heavier bands', 2016);
INSERT INTO collection(name, year) VALUES('Heaviest songs of year', 2012);
INSERT INTO collection(name, year) VALUES('Longest metal songs', 2015);
INSERT INTO collection(name, year) VALUES('Best Thrash metal', 2018);

INSERT INTO trackscollections(track_id, collection_id) VALUES(2, 1);
INSERT INTO trackscollections(track_id, collection_id) VALUES(4, 1);
INSERT INTO trackscollections(track_id, collection_id) VALUES(5, 1);
INSERT INTO trackscollections(track_id, collection_id) VALUES(6, 1);
INSERT INTO trackscollections(track_id, collection_id) VALUES(10, 1);
INSERT INTO trackscollections(track_id, collection_id) VALUES(18, 1);
INSERT INTO trackscollections(track_id, collection_id) VALUES(19, 1);
INSERT INTO trackscollections(track_id, collection_id) VALUES(21, 1);
INSERT INTO trackscollections(track_id, collection_id) VALUES(48, 2);
INSERT INTO trackscollections(track_id, collection_id) VALUES(49, 2);
INSERT INTO trackscollections(track_id, collection_id) VALUES(51, 2);
INSERT INTO trackscollections(track_id, collection_id) VALUES(53, 2);
INSERT INTO trackscollections(track_id, collection_id) VALUES(54, 2);
INSERT INTO trackscollections(track_id, collection_id) VALUES(57, 2);
INSERT INTO trackscollections(track_id, collection_id) VALUES(36, 3);
INSERT INTO trackscollections(track_id, collection_id) VALUES(37, 3);
INSERT INTO trackscollections(track_id, collection_id) VALUES(38, 3);
INSERT INTO trackscollections(track_id, collection_id) VALUES(40, 3);
INSERT INTO trackscollections(track_id, collection_id) VALUES(42, 3);
INSERT INTO trackscollections(track_id, collection_id) VALUES(72, 4);
INSERT INTO trackscollections(track_id, collection_id) VALUES(73, 4);
INSERT INTO trackscollections(track_id, collection_id) VALUES(74, 4);
INSERT INTO trackscollections(track_id, collection_id) VALUES(76, 4);
INSERT INTO trackscollections(track_id, collection_id) VALUES(81, 5);
INSERT INTO trackscollections(track_id, collection_id) VALUES(83, 5);
INSERT INTO trackscollections(track_id, collection_id) VALUES(85, 5);
INSERT INTO trackscollections(track_id, collection_id) VALUES(59, 5);
INSERT INTO trackscollections(track_id, collection_id) VALUES(61, 5);
INSERT INTO trackscollections(track_id, collection_id) VALUES(64, 5);
INSERT INTO trackscollections(track_id, collection_id) VALUES(65, 5);
INSERT INTO trackscollections(track_id, collection_id) VALUES(42, 6);
INSERT INTO trackscollections(track_id, collection_id) VALUES(57, 6);
INSERT INTO trackscollections(track_id, collection_id) VALUES(68, 6);
INSERT INTO trackscollections(track_id, collection_id) VALUES(4, 7);
INSERT INTO trackscollections(track_id, collection_id) VALUES(6, 7);
INSERT INTO trackscollections(track_id, collection_id) VALUES(22, 7);
INSERT INTO trackscollections(track_id, collection_id) VALUES(23, 7);
INSERT INTO trackscollections(track_id, collection_id) VALUES(24, 7);
INSERT INTO trackscollections(track_id, collection_id) VALUES(25, 7);
INSERT INTO trackscollections(track_id, collection_id) VALUES(34, 7);
INSERT INTO trackscollections(track_id, collection_id) VALUES(36, 7);
INSERT INTO trackscollections(track_id, collection_id) VALUES(38, 7);
INSERT INTO trackscollections(track_id, collection_id) VALUES(40, 7);
INSERT INTO trackscollections(track_id, collection_id) VALUES(41, 7);
INSERT INTO trackscollections(track_id, collection_id) VALUES(51, 7);
INSERT INTO trackscollections(track_id, collection_id) VALUES(85, 8);
INSERT INTO trackscollections(track_id, collection_id) VALUES(10, 8);
INSERT INTO trackscollections(track_id, collection_id) VALUES(21, 8);
INSERT INTO trackscollections(track_id, collection_id) VALUES(57, 8);
INSERT INTO trackscollections(track_id, collection_id) VALUES(13, 8);
INSERT INTO trackscollections(track_id, collection_id) VALUES(4, 8);
INSERT INTO trackscollections(track_id, collection_id) VALUES(29, 8);
INSERT INTO trackscollections(track_id, collection_id) VALUES(29, 8);
INSERT INTO trackscollections(track_id, collection_id) VALUES(29, 8);
INSERT INTO trackscollections(track_id, collection_id) VALUES(29, 8);
INSERT INTO trackscollections(track_id, collection_id) VALUES(29, 8);